---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    requirements-file: molecule/default/requirements.yml
driver:
  name: delegated
  vm_username: Administrator
  connection: winrm
  port: 5986
  winrm_transport: ntlm
  winrm_server_cert_validation: ignore
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    template: windows-base-win2019
    snapshot_src: Clean updated minimal install
    memory_mb: 4096
    cpus: 2
    network: VM Network
    datastore: MX500_1TB
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
