---
dependency:
  name: galaxy
driver:
  name: delegated
  hostname: vsphere.matsusoft.com
  username: administrator@vsphere.local
  validate_certs: false
  datacenter: Datacenter1
  esxi_hostname: barney.matsusoft.com
  folder: /
  vm_username: Administrator
  connection: winrm
  port: 5986
  winrm_transport: ntlm
  winrm_server_cert_validation: ignore
lint:
  name: yamllint
platforms:
  - name: instance
    template: windows-base-win2019
    snapshot_src: Clean updated minimal install
    memory_mb: 4096
    cpus: 2
    network: VM Network
    datastore: MX500_1TB
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      host_vars: ../../../../host_vars/
  config_options:
    defaults:
      vault_password_file: /usr/local/bin/op-vault
  log: true
verifier:
  name: testinfra
  lint:
    name: flake8
