---
- name: Use vcenter_password from hostvars
  vars:
    molecule_yml_part:
      driver:
        password: "{{ hostvars[inventory_hostname_short].vcenter_password | default(omit) }}"
  set_fact:
    molecule_yml: "{{ molecule_yml | combine(molecule_yml_part, recursive=true) }}"
  when: hostvars[inventory_hostname_short].vcenter_password is defined
  no_log: true
- name: Use guest_userpassword from hostvars
  vars:
    molecule_yml_part:
      driver:
        vm_password: "{{ hostvars[inventory_hostname_short].guest_userpassword | default(omit) }}"
  set_fact:
    molecule_yml: "{{ molecule_yml | combine(molecule_yml_part, recursive=true) }}"
  when: hostvars[inventory_hostname_short].guest_userpassword is defined
  no_log: true
