---
dependency:
  name: galaxy
driver:
  name: delegated
  vm_username: jpmat
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: inst-lin-${BUILD_NUMBER:-000}
    template: linux-base-ubuntu16
    snapshot_src: Clean updated minimal install
    memory_mb: 2048
    cpus: 2
    network: VM Network
    datastore: MX500_1TB
provisioner:
  name: ansible
verifier:
  name: ansible
